# Generated by Django 5.2.15 on 2026-06-30 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الشركة', max_length=200)),
                ('industry', models.CharField(help_text='مجال العمل / الصناعة', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('website', models.URLField(blank=True, help_text='الموقع الإلكتروني')),
                ('description', models.TextField(blank=True, help_text='نبذة عن الشركة')),
                ('contact_email', models.EmailField(blank=True, help_text='البريد الإلكتروني للتواصل', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GraduateInfoUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='اسم الحقل المراد تعديله', max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_update_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_info_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('TEMP_CERTIFICATE', 'شهادة تخرج مؤقتة'), ('OFFICIAL_CERTIFICATE', 'شهادة تخرج رسمية'), ('CERTIFICATE_REPLACEMENT', 'بدل فاقد شهادة'), ('TRANSCRIPT_AR', 'كشف درجات عربي'), ('TRANSCRIPT_EN', 'كشف درجات إنجليزي'), ('GRADUATION_STATEMENT', 'إفادة تخرج'), ('DEGREE_VERIFICATION', 'خطاب تأكيد درجة'), ('CERTIFICATE_AUTH', 'توثيق شهادة'), ('INFO_UPDATE', 'تحديث بيانات')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم التقديم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('MISSING_DOCUMENTS', 'مستندات ناقصة'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], default='SUBMITTED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='ملاحظات من الخريج')),
                ('internal_notes', models.TextField(blank=True, help_text='ملاحظات داخلية للموظف')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='graduate_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_graduate_requests', to=settings.AUTH_USER_MODEL)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduateRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم التقديم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('MISSING_DOCUMENTS', 'مستندات ناقصة'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم التقديم'), ('UNDER_REVIEW', 'قيد المراجعة'), ('MISSING_DOCUMENTS', 'مستندات ناقصة'), ('APPROVED', 'تمت الموافقة'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='graduate_affairs.graduaterequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduationClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_cleared', models.BooleanField(default=False)),
                ('library_notes', models.CharField(blank=True, max_length=255)),
                ('finance_cleared', models.BooleanField(default=False)),
                ('finance_notes', models.CharField(blank=True, max_length=255)),
                ('labs_cleared', models.BooleanField(default=False)),
                ('labs_notes', models.CharField(blank=True, max_length=255)),
                ('department_cleared', models.BooleanField(default=False)),
                ('department_notes', models.CharField(blank=True, max_length=255)),
                ('housing_cleared', models.BooleanField(default=False)),
                ('housing_notes', models.CharField(blank=True, max_length=255)),
                ('other_cleared', models.BooleanField(default=False)),
                ('other_notes', models.CharField(blank=True, max_length=255)),
                ('overall_status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('IN_PROGRESS', 'جاري التنفيذ'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_clearance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='المسمى الوظيفي', max_length=200)),
                ('description', models.TextField(help_text='الوصف الوظيفي')),
                ('requirements', models.TextField(help_text='متطلبات الوظيفة')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'دوام كامل'), ('PART_TIME', 'دوام جزئي'), ('INTERNSHIP', 'تدريب / Internship'), ('FREELANCE', 'عمل حر / مستقل')], default='FULL_TIME', max_length=20)),
                ('location', models.CharField(help_text='مقر العمل', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='متاح للتقديم')),
                ('deadline', models.DateField(blank=True, help_text='آخر موعد للتقديم', null=True)),
                ('external_link', models.URLField(blank=True, help_text='رابط التقديم الخارجي (إن وجد)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='graduate_affairs.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الفعالية', max_length=200)),
                ('description', models.TextField(help_text='تفاصيل الفعالية')),
                ('event_type', models.CharField(choices=[('WORKSHOP', 'ورشة عمل'), ('SEMINAR', 'ندوة تعريفية'), ('CAREER_FAIR', 'ملتقى توظيفي'), ('TRAINING_COURSE', 'دورة تدريبية')], default='WORKSHOP', max_length=20)),
                ('date', models.DateTimeField(help_text='تاريخ ووقت الفعالية')),
                ('location', models.CharField(help_text='المكان (أو رابط الأونلاين)', max_length=200)),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='الحد الأقصى للحضور (اتركه فارغاً إذا لم يكن هناك حد)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='متاح للتسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='الجهة المقدمة للتدريب (اختياري إذا كانت الكلية هي المنظمة)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_events', to='graduate_affairs.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(help_text='السيرة الذاتية', upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, help_text='خطاب التغطية / الدافع')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('REVIEWED', 'تمت المراجعة'), ('SHORTLISTED', 'القائمة المختصرة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='graduate_affairs.jobposting')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'تم التسجيل'), ('ATTENDED', 'حضر'), ('CANCELLED', 'ملغى')], default='REGISTERED', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='graduate_affairs.trainingevent')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
