# Generated by Django 5.2.9 on 2025-12-16 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_news_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='creator_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All'), ('STUDENTS', 'Students'), ('DOCTORS', 'Doctors')], default='ALL', max_length=20),
        ),
    ]
