# Generated by Django 5.2.9 on 2025-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('STUDENT', 'Student'), ('LEVEL', 'Level'), ('YEAR', 'Academic Year'), ('DEPARTMENT', 'Department'), ('COURSE', 'Course')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
