# Generated by Django 5.2.9 on 2025-12-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_login_required_user_graduation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('DOCTOR', 'Doctor'), ('STUDENT_AFFAIRS', 'Student Affairs'), ('STAFF_AFFAIRS', 'Staff Affairs')], default='STUDENT', max_length=50),
        ),
    ]
