# Generated by Django 5.2.15 on 2026-06-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0004_add_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('DOCTOR', 'Doctor'), ('STUDENT_AFFAIRS', 'Student Affairs'), ('STAFF_AFFAIRS', 'Staff Affairs'), ('HOD', 'Head of Department'), ('DEAN', 'Dean')], default='STUDENT', max_length=50),
        ),
    ]
