# Generated by Django 5.2.15 on 2026-06-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('DOCTOR', 'Doctor'), ('STUDENT_AFFAIRS', 'Student Affairs'), ('STAFF_AFFAIRS', 'Staff Affairs'), ('GRADUATE_AFFAIRS', 'Graduate Affairs')], default='STUDENT', max_length=50),
        ),
    ]
