# Generated by Django 5.2.15 on 2026-07-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
        ('users', '0005_user_department_alter_user_role'),
    ]

    operations = [
    ]
