# Generated by Django 5.2.15 on 2026-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260701_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('DOCTOR', 'Doctor'), ('STUDENT_AFFAIRS', 'Student Affairs'), ('STAFF_AFFAIRS', 'Staff Affairs'), ('HOD', 'Head of Department'), ('DEAN', 'Dean'), ('GRADUATE_AFFAIRS', 'Graduate Affairs')], default='STUDENT', max_length=50),
        ),
    ]
