# Generated by Django 5.2.15 on 2026-06-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPublishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_affairs_approved', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publishings', to='academic.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publishings', to='academic.level')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publishings', to='academic.term')),
            ],
            options={
                'unique_together': {('academic_year', 'term', 'level')},
            },
        ),
    ]
