# Generated by Django 5.2.15 on 2026-06-24 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_resultpublishing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultpublishing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultpublishing',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_publishings', to='academic.specialization'),
        ),
        migrations.AlterUniqueTogether(
            name='resultpublishing',
            unique_together={('academic_year', 'term', 'level', 'specialization')},
        ),
    ]
