# Generated by Django 5.2.15 on 2026-06-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_resultpublishing_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='coursework',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='practical',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('subject', 'academic_year', 'term', 'level', 'specialization')},
        ),
    ]
