# Generated by Django 5.2.15 on 2026-06-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_studentgrade_coursework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('ALL', 'الكل'), ('STUDENT', 'الطلاب'), ('DOCTOR', 'أعضاء هيئة التدريس'), ('STUDENT_AFFAIRS', 'شؤون الطلاب'), ('STAFF_AFFAIRS', 'شؤون الموظفين'), ('GRADUATE_AFFAIRS', 'شؤون الخريجين')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STUDENT_BATCH_UPLOAD', 'Student Batch Upload'), ('DOCTOR_BATCH_UPLOAD', 'Doctor Batch Upload'), ('STAFF_BATCH_UPLOAD', 'Staff Batch Upload'), ('GRADE_UPLOAD', 'Grade Upload'), ('STUDENT_PASSWORD_RESET', 'Student Password Reset'), ('DOCTOR_ASSIGNMENT', 'Doctor Assignment'), ('DOCTOR_UNASSIGNMENT', 'Doctor Unassignment'), ('STUDENT_CREATED', 'Student Created'), ('STUDENT_DELETED', 'Student Deleted'), ('DOCTOR_CREATED', 'Doctor Created'), ('DOCTOR_DELETED', 'Doctor Deleted'), ('GRADE_APPROVED', 'Grade Approved'), ('GRADE_REJECTED', 'Grade Rejected'), ('CERTIFICATE_GENERATED', 'Certificate Generated'), ('GRADUATE_REQUEST_CREATED', 'Graduate Request Created'), ('GRADUATE_REQUEST_UPDATED', 'Graduate Request Updated'), ('NEWS_CREATED', 'News Created')], max_length=50),
        ),
    ]
