# Generated by Django 5.2.15 on 2026-06-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_studentgrade_coursework_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_paid_tuition',
            field=models.BooleanField(default=False),
        ),
    ]
