# Generated by Django 5.2.15 on 2026-06-30 14:15

import uuid
from django.db import migrations, models

def generate_unique_uuids(apps, schema_editor):
    Certificate = apps.get_model('academic', 'Certificate')
    for certificate in Certificate.objects.all():
        certificate.verification_code = uuid.uuid4()
        certificate.save(update_fields=['verification_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_announcement_target_role_alter_auditlog_action'),
    ]

    operations = [
        # Step 1: Add the field without unique=True and allowing nulls temporarily
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(generate_unique_uuids, reverse_code=migrations.RunPython.noop),
        # Step 3: Enforce unique constraint and remove null=True
        migrations.AlterField(
            model_name='certificate',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
