# Generated by Django 5.2.15 on 2026-06-30 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_announcement_target_role_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
