# Generated by Django 5.2.15 on 2026-07-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_student_has_paid_tuition'),
        ('academic', '0006_certificate_verification_code'),
    ]

    operations = [
    ]
