# Generated by Django 5.2.9 on 2025-12-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_examgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='department',
            name='has_specializations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='is_preparatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STUDENT_BATCH_UPLOAD', 'Student Batch Upload'), ('DOCTOR_BATCH_UPLOAD', 'Doctor Batch Upload'), ('STAFF_BATCH_UPLOAD', 'Staff Batch Upload'), ('GRADE_UPLOAD', 'Grade Upload')], max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('PREPARATORY', 'الفرقة الإعدادية'), ('FIRST', 'الفرقة الأولى'), ('SECOND', 'الفرقة الثانية'), ('THIRD', 'الفرقة الثالثة'), ('FOURTH', 'الفرقة الرابعة')], max_length=50),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='academic.department')),
            ],
            options={
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic.specialization'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('PREPARATORY', 'الفرقة الإعدادية'), ('FIRST', 'الفرقة الأولى'), ('SECOND', 'الفرقة الثانية'), ('THIRD', 'الفرقة الثالثة'), ('FOURTH', 'الفرقة الرابعة')], max_length=20)),
                ('semester', models.IntegerField(choices=[(1, 'الفصل الدراسي الأول'), (2, 'الفصل الدراسي الثاني')])),
                ('lecture_hours', models.IntegerField(default=2)),
                ('tutorial_hours', models.IntegerField(default=1)),
                ('lab_hours', models.IntegerField(default=0)),
                ('credit_hours', models.IntegerField(default=3)),
                ('max_grade', models.IntegerField(default=100)),
                ('is_elective', models.BooleanField(default=False)),
                ('elective_group', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.department')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.specialization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='examgrade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examgrade',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='examgrade',
            unique_together={('student', 'subject', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('subject', 'level', 'academic_year')},
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
        migrations.RemoveField(
            model_name='examgrade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachingassignment',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
