# Generated by Django 5.2.9 on 2025-12-18 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_remove_course_department_remove_course_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attendance_weight', models.IntegerField(default=10, help_text='Weight for attendance (e.g., 10)')),
                ('attendance_slots', models.IntegerField(default=14, help_text='Number of attendance sessions')),
                ('quizzes_weight', models.IntegerField(default=10, help_text='Weight for quizzes')),
                ('quiz_count', models.IntegerField(default=2, help_text='Number of quizzes')),
                ('coursework_weight', models.IntegerField(default=10, help_text='Weight for coursework/assignments')),
                ('midterm_weight', models.IntegerField(default=20, help_text='Weight for midterm exam')),
                ('final_weight', models.IntegerField(default=50, help_text='Weight for final exam')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='academicyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('OPEN', 'مفتوح'), ('CLOSED', 'مغلق')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academic.academicyear')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academic.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academic.subject')),
                ('grading_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings', to='academic.gradingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lectures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='academic.courseoffering')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FIRST', 'الترم الأول'), ('SECOND', 'الترم الثاني')], max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academic.academicyear')),
            ],
            options={
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academic.term'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('status', models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غائب')], default='ABSENT', max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.student')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic.courseoffering')),
            ],
            options={
                'unique_together': {('student', 'course_offering', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_grades', models.JSONField(blank=True, default=dict)),
                ('coursework', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('midterm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='academic.student')),
            ],
            options={
                'unique_together': {('student', 'course_offering')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('subject', 'academic_year', 'term', 'level')},
        ),
    ]
