# Generated by Django 5.2.9 on 2025-12-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_doctordeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingtemplate',
            name='practical_weight',
            field=models.IntegerField(default=10, help_text='عملي/شفوي - Practical/Oral weight'),
        ),
        migrations.AddField(
            model_name='gradingtemplate',
            name='written_weight',
            field=models.IntegerField(default=50, help_text='تحريري - Written exam weight'),
        ),
        migrations.AddField(
            model_name='subject',
            name='default_grading_template',
            field=models.ForeignKey(blank=True, help_text='Default grading template for this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academic.gradingtemplate'),
        ),
        migrations.AlterField(
            model_name='gradingtemplate',
            name='attendance_weight',
            field=models.IntegerField(default=0, help_text='Weight for attendance'),
        ),
        migrations.AlterField(
            model_name='gradingtemplate',
            name='coursework_weight',
            field=models.IntegerField(default=40, help_text='اعمال فصلية - Coursework weight'),
        ),
        migrations.AlterField(
            model_name='gradingtemplate',
            name='final_weight',
            field=models.IntegerField(default=0, help_text='Weight for final exam (legacy)'),
        ),
        migrations.AlterField(
            model_name='gradingtemplate',
            name='midterm_weight',
            field=models.IntegerField(default=0, help_text='Weight for midterm exam (legacy)'),
        ),
        migrations.AlterField(
            model_name='gradingtemplate',
            name='quizzes_weight',
            field=models.IntegerField(default=0, help_text='Weight for quizzes'),
        ),
    ]
