# Generated by Django 5.2.9 on 2026-01-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_add_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'جاري الحل'), ('SUBMITTED', 'تم التسليم'), ('TIMEOUT', 'انتهى الوقت'), ('GRADED', 'تم التصحيح')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غائب'), ('EXCUSED', 'بعذر')], default='ABSENT', max_length=10),
        ),
        migrations.CreateModel(
            name='LectureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'السبت'), ('SUN', 'الأحد'), ('MON', 'الاثنين'), ('TUE', 'الثلاثاء'), ('WED', 'الأربعاء'), ('THU', 'الخميس'), ('FRI', 'الجمعة')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(help_text='Hall or Lab name', max_length=100)),
                ('schedule_type', models.CharField(choices=[('LECTURE', 'محاضرة'), ('TUTORIAL', 'سكشن'), ('LAB', 'معمل')], default='LECTURE', max_length=10)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.courseoffering')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academic.lectureschedule'),
        ),
    ]
