# Generated by Django 5.2.9 on 2026-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_studentquizattempt_status_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='final_exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='final_exam_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='final_exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
