# Generated by Django 5.2.10 on 2026-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_fix_attendance_session_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course_offering', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session_number',
        ),
    ]
