# Generated by Django 5.2.12 on 2026-03-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_add_attendance_quizzes_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('general', 'استفسار عام'), ('admission', 'القبول والتسجيل'), ('academic', 'الشؤون الأكاديمية'), ('technical', 'الدعم التقني'), ('complaint', 'شكوى أو اقتراح'), ('other', 'أخرى')], default='general', max_length=20)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),


        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STUDENT_BATCH_UPLOAD', 'Student Batch Upload'), ('DOCTOR_BATCH_UPLOAD', 'Doctor Batch Upload'), ('STAFF_BATCH_UPLOAD', 'Staff Batch Upload'), ('GRADE_UPLOAD', 'Grade Upload'), ('STUDENT_PASSWORD_RESET', 'Student Password Reset'), ('DOCTOR_ASSIGNMENT', 'Doctor Assignment'), ('DOCTOR_UNASSIGNMENT', 'Doctor Unassignment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('target_role', models.CharField(choices=[('ALL', 'الكل'), ('STUDENT', 'الطلاب'), ('DOCTOR', 'أعضاء هيئة التدريس'), ('STUDENT_AFFAIRS', 'شؤون الطلاب'), ('STAFF_AFFAIRS', 'شؤون الموظفين')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('STUDENT', 'رفع طلاب'), ('DOCTOR', 'رفع أعضاء هيئة تدريس'), ('STAFF', 'رفع موظفين'), ('GRADE', 'رفع درجات'), ('CERTIFICATE', 'رفع شهادات')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('errors_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Upload histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
