# Generated by Django 5.2.12 on 2026-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_contactmessage_remove_attendance_session_number_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('OPEN', 'مفتوح'), ('CLOSED', 'مغلق')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STUDENT_BATCH_UPLOAD', 'Student Batch Upload'), ('DOCTOR_BATCH_UPLOAD', 'Doctor Batch Upload'), ('STAFF_BATCH_UPLOAD', 'Staff Batch Upload'), ('GRADE_UPLOAD', 'Grade Upload'), ('STUDENT_PASSWORD_RESET', 'Student Password Reset'), ('DOCTOR_ASSIGNMENT', 'Doctor Assignment'), ('DOCTOR_UNASSIGNMENT', 'Doctor Unassignment'), ('STUDENT_CREATED', 'Student Created'), ('STUDENT_DELETED', 'Student Deleted'), ('DOCTOR_CREATED', 'Doctor Created'), ('DOCTOR_DELETED', 'Doctor Deleted'), ('GRADE_APPROVED', 'Grade Approved'), ('GRADE_REJECTED', 'Grade Rejected'), ('CERTIFICATE_GENERATED', 'Certificate Generated'), ('NEWS_CREATED', 'News Created')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ESSAY', 'Essay'), ('IMAGE', 'Image-based'), ('MIXED', 'Mixed (MCQ + Essay)')], default='MCQ', max_length=20),
        ),
    ]
